#!/bin/bash

result=`cd /src/letter-avatars && git pull | grep "Already up-to-date"`

if [ -z "$result" ]; then
   echo "updating..."
   cd /var/discourse && ./launcher bootstrap letter_avatars && ./launcher destroy letter_avatars && ./launcher start letter_avatars
fi

